/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StocRouteImport } from './routes/stoc'
import { Route as IndexRouteImport } from './routes/index'

const StocRoute = StocRouteImport.update({
  id: '/stoc',
  path: '/stoc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stoc': typeof StocRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stoc': typeof StocRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stoc': typeof StocRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stoc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stoc'
  id: '__root__' | '/' | '/stoc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StocRoute: typeof StocRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stoc': {
      id: '/stoc'
      path: '/stoc'
      fullPath: '/stoc'
      preLoaderRoute: typeof StocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StocRoute: StocRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
